"""Initial migration.

Revision ID: 10214081f29d
Revises: 55f699362996
Create Date: 2024-01-02 18:38:22.582826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10214081f29d'
down_revision = '55f699362996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###
